// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Clear():Promise<main.APIResponse>;

export function Generate(arg1:main.GenerateParams):Promise<main.APIResponse>;

export function GetDataDir():Promise<string>;

export function GetVersion():Promise<string>;

export function LoadConfig():Promise<main.SavedConfig>;

export function OpenDataDir():Promise<void>;

export function OpenExternalLink(arg1:string):Promise<void>;

export function Status():Promise<main.APIResponse>;
